language: cpp
compiler: g++
sudo: required
dist: trusty
before_install:
  - add-apt-repository ppa:ubuntu-toolchain-r/test
  - apt-get update
  - apt-get install g++-5
script: 
  - cd ./build
  - cmake .
  - make
