language: cpp
compiler: 
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9.2 g++-4.9.2
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  - g++ --version
  - sudo apt-get update -qq
  - git submodule update --init --recursive
before_script: cmake .
script: make
