language: cpp
compiler: g++
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y
  - CXX=g++-5
script: 
  - cd ./build
  - cmake .
  - make
